# -*- mode: ruby -*-
# vi: set ft=ruby ts=2 sw=2 et sua= inex= :

config_file = File.join(File.dirname(__FILE__), "/config.ini")
options = {}
File.foreach(config_file) { |line|
  option, value = line.split("=")
  option = option.strip()
  if !value.nil?
    value = value.strip()
    options[option] = value
  end
}

nodes = {
  "grizzly" => {
    "box" => "openstack-user/precise-grizzly",
    "ip" => "#{options['grizzly_ip']}",
    "ip2" => "#{options['grizzly_ip2']}",
    "memory" => 4096,
    "role" => "openstack",
    "cpus" => 2,
    "nfs_share_name" => "grizzly"
  },
  "icehouse" => {
    "box" => "openstack-user/trusty-icehouse",
    "ip" => "#{options['icehouse_ip']}",
    "ip2" => "#{options['icehouse_ip2']}",
    "memory" => 4096,
    "role" => "openstack",
    "cpus" => 2,
    "nfs_share_name" => "icehouse"
  },
  "juno" => {
    "box" => "openstack-user/trusty-juno",
    "ip" => "#{options['juno_ip']}",
    "ip2" => "#{options['juno_ip2']}",
    "memory" => 4096,
    "role" => "openstack",
    "cpus" => 2,
    "nfs_share_name" => "juno"
  },
  "cloudferry" => {
    "box" => "hashicorp/precise64",
    "ip" => "#{options['cloudferry_ip']}",
    "ip2" => "#{options['cloudferry_ip2']}",
    "memory" => 2048,
    "role" => "lab"
  },
  "nfs" => {
    "box" => "openstack-user/nfs-server",
    "ip" => "#{options['nfs_ip']}",
    "ip2" => "#{options['nfs_ip2']}",
    "memory" => 1024,
    "cpus" => 1
  },
  "grizzly_juno_src" => {
    "box" => "grizzly_juno/src",
    "url" => "http://172.18.236.71/grizzly_juno/src.json",
    "ip" => "#{options['grizzly_ip']}",
    "ip2" => "#{options['grizzly_ip2']}",
    "memory" => 4096,
    "role" => "openstack",
    "hostname" => "grizzly",
    "release" => "grizzly",
    "cpus" => 2,
    "nfs_share_name" => "grizzly"
  },
  "grizzly_juno_dst" => {
    "box" => "grizzly_juno/dst",
    "url" => "http://172.18.236.71/grizzly_juno/dst.json",
    "ip" => "#{options['juno_ip']}",
    "ip2" => "#{options['juno_ip2']}",
    "memory" => 4096,
    "role" => "openstack",
    "hostname" => "juno",
    "release" => "juno",
    "cpus" => 2,
    "nfs_share_name" => "juno"
  },
  "grizzly_juno_nfs" => {
    "box" => "grizzly_juno/nfs",
    "url" => "http://172.18.236.71/grizzly_juno/nfs.json",
    "ip" => "#{options['nfs_ip']}",
    "ip2" => "#{options['nfs_ip2']}",
    "memory" => 1024,
    "hostname" => "nfs",
    "cpus" => 1
  },
  "icehouse_juno_src" => {
    "box" => "icehouse_juno/src",
    "url" => "http://172.18.236.71/icehouse_juno/src.json",
    "ip" => "#{options['icehouse_ip']}",
    "ip2" => "#{options['icehouse_ip2']}",
    "memory" => 4096,
    "role" => "openstack",
    "hostname" => "icehouse",
    "release" => "icehouse",
    "cpus" => 2,
    "nfs_share_name" => "icehouse"
  },
  "icehouse_juno_dst" => {
    "box" => "icehouse_juno/dst",
    "url" => "http://172.18.236.71/icehouse_juno/dst.json",
    "ip" => "#{options['juno_ip']}",
    "ip2" => "#{options['juno_ip2']}",
    "memory" => 4096,
    "role" => "openstack",
    "hostname" => "juno",
    "release" => "juno",
    "cpus" => 2,
    "nfs_share_name" => "juno"
  },
  "icehouse_juno_nfs" => {
    "box" => "icehouse_juno/nfs",
    "url" => "http://172.18.236.71/icehouse_juno/nfs.json",
    "ip" => "#{options['nfs_ip']}",
    "ip2" => "#{options['nfs_ip2']}",
    "memory" => 1024,
    "hostname" => "nfs",
    "cpus" => 1
  },
}

options['http_proxy'] ||= ""
options['https_proxy'] ||= ""
options['ftp_proxy'] ||= ""

new_nfs_name = ENV.fetch("SHARED_NFS_NAME", false)

Vagrant.require_version '>= 1.6.0'

if not options['http_proxy'].empty?
    unless Vagrant.has_plugin?("vagrant-proxyconf")
        system('vagrant plugin install vagrant-proxyconf')
    end
end

Vagrant.configure(2) do |config|

  if Vagrant.has_plugin?("vagrant-proxyconf")
    config.proxy.http     = "#{options['http_proxy']}"
    config.proxy.https    = "#{options['https_proxy']}"
    config.proxy.ftp      = "#{options['ftp_proxy']}"
    config.proxy.no_proxy = "localhost,127.0.0.1,"\
                            "#{options['grizzly_ip']},"\
                            "#{options['icehouse_ip']},"\
                            "#{options['juno_ip']},"\
                            "#{options['cloudferry_ip']},"\
                            "#{options['nfs_ip']}"
  end

  etc_hosts = nodes.map { |name, data| [data["ip"], name].join(' ') }.join("\n")

  nodes.each do |nodename, nodedata|
    config.vm.define nodename do |thisnode|
      if nodedata.key?("url")
        thisnode.vm.box_url = nodedata["url"]
      end

      thisnode.vm.box = nodedata['box']
      thisnode.vm.hostname = nodedata.fetch("hostname", nodename)
      thisnode.vm.provision "shell", inline: "echo '#{etc_hosts}' >> /etc/hosts"
      thisnode.vm.provision "shell",
        path: "./provision/keys.sh",
        args: [ "--public-key", File.read("#{ENV["HOME"]}/#{options['public_key_path']}").strip() ]

      case nodedata.fetch("role", "")
        when "openstack"
          thisnode.vm.provision "shell", path: "./provision/configure_networking.sh", args: ['eth1', 'br-ex', nodedata['ip']]
          thisnode.vm.provision "shell", path: "./provision/configure_networking.sh", args: ['eth2', 'br-ex2', nodedata['ip2']]
          thisnode.vm.provision "shell", path: "./provision/configure_openstack.sh", args: [nodedata['ip'], nodename]
          thisnode.vm.provision "shell", path: "./provision/create_disks_swift.sh"

          if nodename == "icehouse" then
            thisnode.vm.provision "shell", path: "./provision/cleanup_nova_instances.sh"
          end

          old_nfs_name = nodedata.fetch("nfs_share_name")
          if new_nfs_name and new_nfs_name != old_nfs_name
          then
            thisnode.vm.provision "shell",
              path: "./provision/configure_nfs.sh",
              args: [old_nfs_name, new_nfs_name]
          end
        when "lab"
          config.vm.provision "shell", path: "./provision/prerequisites.sh"
          thisnode.vm.provision "shell",
            path: "./provision/cloudferry.sh"
          if File.exist?(File.join(Dir.home, ".ssh/id_rsa")) then
            thisnode.vm.provision "file",
              source: "~/.ssh/id_rsa",
              destination: "/home/vagrant/.ssh/id_rsa"
          end
      end

      thisnode.vm.network "private_network", ip: nodedata['ip'], auto_config: (nodedata.fetch("role", "") != "openstack"), nic_type: "virtio"
      thisnode.vm.network "private_network", ip: nodedata['ip2'], auto_config: (nodedata.fetch("role", "") != "openstack"), nic_type: "virtio"

      thisnode.vm.provider "virtualbox" do |v|
        v.memory = nodedata.fetch("memory", 1024)
        v.cpus = nodedata.fetch("cpus", 2)
        v.customize ["modifyvm", :id, "--nicpromisc2", "allow-all"]
        v.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "90"]
        v.customize ["modifyvm", :id, "--nictype1", "virtio"]
      end
    end
  end
end
